// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonInvestBatch.Infrastructure.Persistence;

#nullable disable

namespace PokemonInvestBatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260815032212_AddPokedex")]
    partial class AddPokedex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Card", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("AnyBucketAtCap")
                        .HasColumnType("boolean")
                        .HasColumnName("any_bucket_at_cap");

                    b.Property<DateTimeOffset?>("DelistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delisted_at");

                    b.Property<DateTimeOffset?>("DelistedProbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delisted_probed_at");

                    b.Property<int>("FailureStreak")
                        .HasColumnType("integer")
                        .HasColumnName("failure_streak");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset?>("GoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gone_at");

                    b.Property<DateTimeOffset?>("ImageFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("image_fetched_at");

                    b.Property<string>("ImageHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("image_hash");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LastVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visited_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NearMissAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("near_miss_at");

                    b.Property<DateTimeOffset?>("NotACardAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_a_card_at");

                    b.Property<double?>("ObservedSalesPerDay")
                        .HasColumnType("double precision")
                        .HasColumnName("observed_sales_per_day");

                    b.Property<DateTimeOffset?>("QuarantinedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_until");

                    b.Property<DateTimeOffset?>("RefreshRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_requested_at");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint")
                        .HasColumnName("set_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("GoneAt")
                        .HasDatabaseName("ix_cards_gone_at")
                        .HasFilter("gone_at IS NOT NULL");

                    b.HasIndex("LastVisitedAt")
                        .HasDatabaseName("ix_cards_last_visited_at");

                    b.HasIndex("RefreshRequestedAt")
                        .HasDatabaseName("ix_cards_refresh_requested_at")
                        .HasFilter("refresh_requested_at IS NOT NULL");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_cards_set_id");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardPopulation", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<string>("Grader")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("grader");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.HasKey("CardId", "Grader", "Grade", "ObservedAt")
                        .HasName("pk_populations");

                    b.ToTable("populations", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardPriceMonth", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.HasKey("CardId", "Tier", "Month", "ObservedAt")
                        .HasName("pk_price_months");

                    b.ToTable("price_months", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("LastWalkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_walked_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_sets");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sets_slug");

                    b.ToTable("sets", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardSpeciesLink", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<short>("Method")
                        .HasColumnType("smallint")
                        .HasColumnName("method");

                    b.HasKey("CardId", "SpeciesId")
                        .HasName("pk_card_species");

                    b.HasIndex("SpeciesId", "CardId")
                        .HasDatabaseName("ix_card_species_species_id_card_id");

                    b.ToTable("card_species", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardTagging", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<short>("Method")
                        .HasColumnType("smallint")
                        .HasColumnName("method");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TaggedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tagged_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CardId")
                        .HasName("pk_card_tagging");

                    b.ToTable("card_tagging", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.KnownFingerprint", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.Property<string>("SampleUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sample_url");

                    b.HasKey("Hash")
                        .HasName("pk_fingerprints");

                    b.ToTable("fingerprints", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.PageVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("FingerprintHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_hash");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_visits_fetched_at");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.ParseFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("FingerprintHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_hash");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_parse_failures");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_parse_failures_fetched_at");

                    b.ToTable("parse_failures", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<string>("GradeTier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("grade_tier");

                    b.Property<int?>("ListedPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("listed_price_cents");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<DateOnly>("SoldOn")
                        .HasColumnType("date")
                        .HasColumnName("sold_on");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CardId", "SoldOn")
                        .HasDatabaseName("ix_sales_card_id_sold_on");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_source_source_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SetDetail", b =>
                {
                    b.Property<long>("SetId")
                        .HasColumnType("bigint")
                        .HasColumnName("set_id");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Era")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("era");

                    b.Property<short>("MatchStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("match_status");

                    b.Property<DateOnly?>("ReleasedOn")
                        .HasColumnType("date")
                        .HasColumnName("released_on");

                    b.Property<string>("Series")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("series");

                    b.HasKey("SetId")
                        .HasName("pk_set_details");

                    b.ToTable("set_details", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Species", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("color");

                    b.Property<int?>("EvolvesFromSpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("evolves_from_species_id");

                    b.Property<short>("Generation")
                        .HasColumnType("smallint")
                        .HasColumnName("generation");

                    b.Property<string>("GradientEnd")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("gradient_end");

                    b.Property<string>("GradientStart")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("gradient_start");

                    b.Property<string>("Habitat")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("habitat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint")
                        .HasColumnName("stage");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("EvolvesFromSpeciesId")
                        .HasDatabaseName("ix_species_evolves_from_species_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_species_slug");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesEggGroup", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<string>("EggGroup")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("egg_group");

                    b.HasKey("SpeciesId", "EggGroup")
                        .HasName("pk_species_egg_groups");

                    b.ToTable("species_egg_groups", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesName", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<string>("Language")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("SpeciesId", "Language")
                        .HasName("pk_species_names");

                    b.ToTable("species_names", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesType", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("slot");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("SpeciesId", "Slot")
                        .HasName("pk_species_types");

                    b.ToTable("species_types", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.TcgdexEnrichment", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("card_number");

                    b.Property<int?>("SetOfficialSize")
                        .HasColumnType("integer")
                        .HasColumnName("set_official_size");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TcgdexCardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tcgdex_card_id");

                    b.Property<string>("TcgdexName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tcgdex_name");

                    b.Property<string>("TcgdexSetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tcgdex_set_id");

                    b.Property<string>("TcgdexVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tcgdex_version");

                    b.HasKey("CardId", "ComputedAt")
                        .HasName("pk_tcgdex_enrichments");

                    b.ToTable("tcgdex_enrichments", (string)null);
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Card", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.CardSet", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cards_sets_set_id");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardPopulation", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_populations_cards_card_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardPriceMonth", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_months_cards_card_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardSpeciesLink", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_species_cards_card_id");

                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_species_species_species_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.CardTagging", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_card_tagging_cards_card_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Sale", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_cards_card_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SetDetail", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.CardSet", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_set_details_sets_set_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.Species", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Species", null)
                        .WithMany()
                        .HasForeignKey("EvolvesFromSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_species_species_evolves_from_species_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesEggGroup", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_egg_groups_species_species_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesName", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_names_species_species_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.SpeciesType", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_types_species_species_id");
                });

            modelBuilder.Entity("PokemonInvestBatch.Infrastructure.Persistence.TcgdexEnrichment", b =>
                {
                    b.HasOne("PokemonInvestBatch.Infrastructure.Persistence.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tcgdex_enrichments_cards_card_id");
                });
#pragma warning restore 612, 618
        }
    }
}
